# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_card.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 444)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 111, 21))
        self.label.setObjectName("label")
        self.new_rule_card_but = QtWidgets.QPushButton(self.centralwidget)
        self.new_rule_card_but.setGeometry(QtCore.QRect(20, 50, 591, 51))
        self.new_rule_card_but.setObjectName("new_rule_card_but")
        self.new_tip_card_but = QtWidgets.QPushButton(self.centralwidget)
        self.new_tip_card_but.setGeometry(QtCore.QRect(20, 120, 591, 51))
        self.new_tip_card_but.setObjectName("new_tip_card_but")
        self.new_history_card_but = QtWidgets.QPushButton(self.centralwidget)
        self.new_history_card_but.setGeometry(QtCore.QRect(20, 190, 591, 51))
        self.new_history_card_but.setObjectName("new_history_card_but")
        self.new_point_card_but = QtWidgets.QPushButton(self.centralwidget)
        self.new_point_card_but.setGeometry(QtCore.QRect(20, 260, 591, 51))
        self.new_point_card_but.setObjectName("new_point_card_but")
        self.close_but = QtWidgets.QPushButton(self.centralwidget)
        self.close_but.setGeometry(QtCore.QRect(510, 330, 101, 51))
        self.close_but.setObjectName("close_but")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Добавить карточки"))
        self.new_rule_card_but.setText(_translate("MainWindow", "Создание новой Карты с описанием игры (Карты правил, Завершающие карты)"))
        self.new_tip_card_but.setText(_translate("MainWindow", "Создание новой Карты подсказок"))
        self.new_history_card_but.setText(_translate("MainWindow", "Создание новой Игровой карты с историей"))
        self.new_point_card_but.setText(_translate("MainWindow", "Создание новой Карты очков"))
        self.close_but.setText(_translate("MainWindow", "Закрыть"))
