# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'history_card_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1245, 612)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 40, 231, 16))
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(50, 120, 291, 71))
        self.groupBox.setObjectName("groupBox")
        self.open_radio = QtWidgets.QRadioButton(self.groupBox)
        self.open_radio.setGeometry(QtCore.QRect(20, 20, 141, 17))
        self.open_radio.setChecked(False)
        self.open_radio.setObjectName("open_radio")
        self.closed_radio = QtWidgets.QRadioButton(self.groupBox)
        self.closed_radio.setGeometry(QtCore.QRect(20, 40, 151, 17))
        self.closed_radio.setChecked(True)
        self.closed_radio.setObjectName("closed_radio")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(50, 240, 551, 141))
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 210, 131, 16))
        self.label_2.setObjectName("label_2")
        self.card_prescription = QtWidgets.QLineEdit(self.centralwidget)
        self.card_prescription.setGeometry(QtCore.QRect(170, 400, 431, 21))
        self.card_prescription.setObjectName("card_prescription")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 400, 101, 16))
        self.label_3.setObjectName("label_3")
        self.card_scene = QtWidgets.QLineEdit(self.centralwidget)
        self.card_scene.setGeometry(QtCore.QRect(170, 440, 431, 21))
        self.card_scene.setObjectName("card_scene")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 440, 101, 16))
        self.label_4.setObjectName("label_4")
        self.card_valid_date = QtWidgets.QLineEdit(self.centralwidget)
        self.card_valid_date.setGeometry(QtCore.QRect(170, 480, 431, 21))
        self.card_valid_date.setObjectName("card_valid_date")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 480, 101, 16))
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(50, 80, 111, 16))
        self.label_7.setObjectName("label_7")
        self.card_number = QtWidgets.QLineEdit(self.centralwidget)
        self.card_number.setGeometry(QtCore.QRect(170, 80, 113, 20))
        self.card_number.setObjectName("card_number")
        self.create_n_continue_but = QtWidgets.QPushButton(self.centralwidget)
        self.create_n_continue_but.setGeometry(QtCore.QRect(50, 520, 551, 41))
        self.create_n_continue_but.setObjectName("create_n_continue_but")
        self.submit_buttons = QtWidgets.QWidget(self.centralwidget)
        self.submit_buttons.setGeometry(QtCore.QRect(660, 460, 551, 61))
        self.submit_buttons.setObjectName("submit_buttons")
        self.save_n_next_but = QtWidgets.QPushButton(self.submit_buttons)
        self.save_n_next_but.setGeometry(QtCore.QRect(0, 10, 221, 41))
        self.save_n_next_but.setObjectName("save_n_next_but")
        self.save_n_close_but = QtWidgets.QPushButton(self.submit_buttons)
        self.save_n_close_but.setGeometry(QtCore.QRect(230, 10, 221, 41))
        self.save_n_close_but.setObjectName("save_n_close_but")
        self.close_but = QtWidgets.QPushButton(self.submit_buttons)
        self.close_but.setGeometry(QtCore.QRect(460, 10, 91, 41))
        self.close_but.setObjectName("close_but")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(660, 199, 321, 121))
        self.groupBox_3.setObjectName("groupBox_3")
        self.curr_tip = QtWidgets.QTextEdit(self.groupBox_3)
        self.curr_tip.setGeometry(QtCore.QRect(10, 20, 301, 91))
        self.curr_tip.setReadOnly(True)
        self.curr_tip.setObjectName("curr_tip")
        self.new_choice_but = QtWidgets.QPushButton(self.centralwidget)
        self.new_choice_but.setGeometry(QtCore.QRect(1000, 70, 211, 81))
        self.new_choice_but.setObjectName("new_choice_but")
        self.new_point_card_but = QtWidgets.QPushButton(self.centralwidget)
        self.new_point_card_but.setGeometry(QtCore.QRect(1000, 330, 211, 81))
        self.new_point_card_but.setObjectName("new_point_card_but")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(660, 69, 321, 121))
        self.groupBox_2.setObjectName("groupBox_2")
        self.curr_choices = QtWidgets.QTextEdit(self.groupBox_2)
        self.curr_choices.setGeometry(QtCore.QRect(10, 20, 301, 91))
        self.curr_choices.setReadOnly(True)
        self.curr_choices.setObjectName("curr_choices")
        self.new_tip_card_but = QtWidgets.QPushButton(self.centralwidget)
        self.new_tip_card_but.setGeometry(QtCore.QRect(1000, 200, 211, 81))
        self.new_tip_card_but.setObjectName("new_tip_card_but")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(660, 329, 321, 121))
        self.groupBox_4.setObjectName("groupBox_4")
        self.curr_points = QtWidgets.QTextEdit(self.groupBox_4)
        self.curr_points.setGeometry(QtCore.QRect(10, 20, 301, 91))
        self.curr_points.setReadOnly(True)
        self.curr_points.setObjectName("curr_points")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1245, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Создание новой Игровой карты с историей"))
        self.label.setText(_translate("MainWindow", "Создание новой Игровой карты с историей"))
        self.groupBox.setTitle(_translate("MainWindow", "Открыта или закрыта (прочитана или не прочитана)"))
        self.open_radio.setText(_translate("MainWindow", "Открыта (прочитана)"))
        self.closed_radio.setText(_translate("MainWindow", "Закрыта (не прочитана)"))
        self.label_2.setText(_translate("MainWindow", "Надпись на самой карте"))
        self.label_3.setText(_translate("MainWindow", "Давность действия"))
        self.label_4.setText(_translate("MainWindow", "Место действия"))
        self.label_5.setText(_translate("MainWindow", "Дата действия"))
        self.label_7.setText(_translate("MainWindow", "Номер карты (целое)"))
        self.create_n_continue_but.setText(_translate("MainWindow", "Создать карту и перейти к добавлению следующих данных"))
        self.save_n_next_but.setText(_translate("MainWindow", "Сохранить и добавить следующую"))
        self.save_n_close_but.setText(_translate("MainWindow", "Сохранить и закрыть"))
        self.close_but.setText(_translate("MainWindow", "Закрыть"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Карта подсказки"))
        self.curr_tip.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Нет карты подсказки</p></body></html>"))
        self.new_choice_but.setText(_translate("MainWindow", "Создание нового варианта ответа"))
        self.new_point_card_but.setText(_translate("MainWindow", "Создание новой Карты очков"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Варианты ответа"))
        self.curr_choices.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Нет вариантов ответа</p></body></html>"))
        self.new_tip_card_but.setText(_translate("MainWindow", "Создание новой Карты подсказки"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Карты очков"))
        self.curr_points.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Нет карт очков</p></body></html>"))
