# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'point_card_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(658, 203)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 40, 191, 16))
        self.label.setObjectName("label")
        self.save_n_next_but = QtWidgets.QPushButton(self.centralwidget)
        self.save_n_next_but.setGeometry(QtCore.QRect(50, 110, 221, 41))
        self.save_n_next_but.setObjectName("save_n_next_but")
        self.save_n_close_but = QtWidgets.QPushButton(self.centralwidget)
        self.save_n_close_but.setGeometry(QtCore.QRect(280, 110, 221, 41))
        self.save_n_close_but.setObjectName("save_n_close_but")
        self.close_but = QtWidgets.QPushButton(self.centralwidget)
        self.close_but.setGeometry(QtCore.QRect(510, 110, 91, 41))
        self.close_but.setObjectName("close_but")
        self.card_score_label = QtWidgets.QLabel(self.centralwidget)
        self.card_score_label.setGeometry(QtCore.QRect(50, 70, 191, 16))
        self.card_score_label.setObjectName("card_score_label")
        self.card_score = QtWidgets.QLineEdit(self.centralwidget)
        self.card_score.setGeometry(QtCore.QRect(250, 70, 351, 20))
        self.card_score.setObjectName("card_score")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 658, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Создание новой Карты подсказок"))
        self.label.setText(_translate("MainWindow", "Создание новой Карты подсказок"))
        self.save_n_next_but.setText(_translate("MainWindow", "Сохранить и добавить следующую"))
        self.save_n_close_but.setText(_translate("MainWindow", "Сохранить и закрыть"))
        self.close_but.setText(_translate("MainWindow", "Закрыть"))
        self.card_score_label.setText(_translate("MainWindow", "Количество очков для варианта"))
